parameters:
    moaction_jsonrpc.server.class: Moaction\Jsonrpc\Server\BasicServer
    moaction_jsonrpc.client.class: Moaction\Jsonrpc\Client\ClientBasic

services:
    moaction_jsonrpc.server:
        class: %moaction_jsonrpc.server.class%